/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "text-main": "#3D3D3D",
        "on-tertiary-container": "#004568",
        "surface-tint": "#176c33",
        "primary-fixed-dim": "#86d993",
        "surface-container-high": "#ede7e1",
        "on-surface": "#1d1b18",
        "surface-container-low": "#f8f3ed",
        "canvas-cream": "#FFF9F3",
        "surface-bright": "#fef8f2",
        "tertiary-fixed": "#cbe6ff",
        "surface-dim": "#dfd9d3",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "success-soft": "#E1F2E5",
        "primary-container": "#6dbe7b",
        "on-secondary-fixed-variant": "#6f3800",
        "inverse-on-surface": "#f6f0ea",
        "on-primary-fixed": "#002109",
        "on-tertiary-fixed": "#001e30",
        "surface-container": "#f3ede7",
        "friendly-sky": "#7CC6FE",
        "secondary-fixed-dim": "#ffb780",
        "tertiary-container": "#69b4eb",
        "surface-container-lowest": "#ffffff",
        "warm-bonding": "#F4A261",
        "on-primary-container": "#004b1e",
        "secondary-fixed": "#ffdcc4",
        "on-tertiary-fixed-variant": "#004b71",
        "secondary": "#8e4e14",
        "primary": "#176c33",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-variant": "#e7e2dc",
        "on-primary-fixed-variant": "#005322",
        "on-secondary-container": "#783d01",
        "on-primary": "#ffffff",
        "secondary-container": "#ffab69",
        "inverse-surface": "#32302c",
        "warning-soft": "#FDF0E6",
        "surface-container-highest": "#e7e2dc",
        "on-secondary-fixed": "#2f1400",
        "surface": "#fef8f2",
        "outline-variant": "#bfc9bc",
        "on-surface-variant": "#40493f",
        "on-tertiary": "#ffffff",
        "background": "#fef8f2",
        "error-container": "#ffdad6",
        "inverse-primary": "#86d993",
        "tertiary": "#006494",
        "on-background": "#1d1b18",
        "primary-fixed": "#a2f6ad",
        "outline": "#707a6e",
        "tertiary-fixed-dim": "#8ecdff",
        "growth-green": "#6DBE7B"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "margin-mobile": "20px",
        gutter: "16px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        unit: "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        "headline-md": ["Nunito Sans"],
        "label-sm": ["Nunito Sans"],
        "headline-lg": ["Nunito Sans"],
        "body-md": ["Nunito Sans"],
        "body-lg": ["Nunito Sans"],
        "label-lg": ["Nunito Sans"],
        "headline-lg-mobile": ["Nunito Sans"]
      },
      fontSize: {
        "xs": ["13px", { lineHeight: "18px" }],
        "sm": ["15px", { lineHeight: "22px" }],
        "base": ["17px", { lineHeight: "26px" }],
        "lg": ["19px", { lineHeight: "28px" }],
        "xl": ["21px", { lineHeight: "30px" }],
        "2xl": ["25px", { lineHeight: "34px" }],
        "3xl": ["31px", { lineHeight: "38px" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "body-md": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "body-lg": ["19px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
}
